- CHANGELOG.md
- package-lock.json
- package.json
- packages/assets/icons/icon-minus.svg
- packages/assets/icons/icon-plus.svg
The commits were cherry picked from upstream, except for the last commit, which I added.
> nhsuk-frontend v6.1.1

- .github/workflows/release.yml
- netlify.toml
- site/views/page-not-found.njk
See individual commits for details.
> [DSI-44] Various changes for the Netlify deploy

- CHANGELOG.md
- packages/assets/icons/icon-arrow-right-circle.svg
- packages/components/action-link/_action-link.scss
- packages/components/action-link/template.njk
- packages/components/breadcrumb/_breadcrumb.scss
- packages/components/checkboxes/_checkboxes.scss
- packages/components/input/_input.scss
- packages/components/radios/_radios.scss
- packages/components/select/_select.scss
- packages/components/textarea/_textarea.scss
- packages/core/settings/_colours.scss
- packages/core/styles/_icons.scss
- packages/core/styles/_typography.scss
- packages/core/tools/_links.scss
- site/views/design-system/components/breadcrumbs/index.njk
- site/views/design-system/styles/colour/index.njk
- site/views/design-system/styles/icons/index.njk
Please see the individual commits for details.
> Second batch of work mainly for the public website

- packages/components/checkboxes/_checkboxes.scss
- packages/components/radios/_radios.scss
- packages/core/settings/_globals.scss
- packages/core/tools/_functions.scss
- packages/core/tools/_shape-arrow.scss
- packages/core/tools/_typography.scss
- packages/core/utilities/_grid-widths.scss
- packages/core/vendor/sass-mq.scss
Thanks to Adrian @ The Bureau for the suggestion; I ran the instructions outlined in https://sass-lang.com/documentation/breaking-changes/slash-div#automatic-migration.
```shell
$ npm install -g sass-migrator
$ sass-migrator division **/*.scss
```
Ran through the docs site and everything seems normal.
> [DSI-45] Fix Sass deprecations

- packages/components/back-link/_back-link.scss
- packages/components/details/_details.scss
- packages/core/styles/_icons.scss
See individual commits for details.
> Couple of colour changes from the pairing session on Tue 22 Nov

- README.md
- docs/contributing/application-architecture.md
- docs/contributing/browser-support.md
- docs/contributing/coding-standards.md
- docs/contributing/git-style-guide.md
- docs/contributing/running-locally.md
- docs/contributing/testing.md
- docs/contributing/tooling.md
- docs/installation/installing-compiled.md
- docs/installation/installing-with-npm.md
See individual commits for details.
> Various doc updates

- site/views/_includes/design-example.njk
- site/views/design-system/styles/spacing/index.njk
Also updated text content in the design-example.njk
> Updated Spacing text content.

- packages/components/back-link/_back-link.scss
- site/styles/app/_side-nav.scss
> Updated colors for side nav links and back link

- site/views/design-system/styles/layout/index.njk
- site/views/design-system/styles/typography/index.njk
- site/views/design-system/styles/typography/lists/index.njk
> Content updates to Typography and Layout page

- site/styles/app/_side-nav.scss
Enable sticky side bar nav across site
> Added position: sticky for side nav

- site/views/design-system/styles/layout/index.njk
- site/views/design-system/styles/spacing/index.njk
- site/views/design-system/styles/typography/index.njk
- site/views/design-system/styles/typography/lists/index.njk
> Text content amends to Layout, Typography and Spacing pages

- site/views/_includes/layout.njk
- site/views/accessibility/index.njk
Added hideContact property to layout to hide the NHS "Share your findings on Github" section across the site.
> Removed NHS Github section by adding property in layout

- packages/core/settings/_colours.scss
- site/styles/app/_utilities.scss
- site/views/design-system/styles/colour/index.njk
Rewrite of the colour page.
Added a subnav of in page links to colours page.
Added scroll-behaviour: smooth in utilities.scss, to enable smooth scrolling in page links site wide.
Added a link to Stark for Figma under contrast checking tools.
Added new colour variables from the content doc to the Design System _colours.scss file.
> Colour page update

- site/scripts/design-example.js
Addresses issues with copy to clipboard function
- execCommand is deprecated
- Breaks keyboard navigation as focus returns to document head on DOM updates
- Hidden content <span> disappears from buttons as content is overwritten with innerText manually
> Fixed bugs with copy to clipboard function in design examples

- packages/core/settings/_colours.scss
- site/views/design-system/styles/colour/index.njk
brand-orange-1 hex code was incorrect. Updated to reflect Figma design system.
> Corrected brand-orange-1 hex code

- site/views/index.njk
Update to the home content. Done as an experiment to get nunjucks, node.js, etc. installed on my machine so I can do edits in the future.
* Removed the 3 cards at the top. Moved these links to "quick links" and a new clickable card
* Added an External links section to the "quick links" sidenav
* Added content talking about and linking to the various sections of the design system
* Accessibility consideration section at the bottom
> Home content update

- CHANGELOG.md
- package-lock.json
- package.json
- site/views/design-system/components/tag/colours/index.njk
Add further descriptions on what has changed since the last release in March: https://github.com/ourfuturehealth/design-system-toolkit/releases
> Release v2.0.0-alpha.4

- site/views/_includes/_side-nav.njk
- site/views/get-started/guidance-for-design/_breadcrumb.njk
- site/views/get-started/guidance-for-design/index.njk
- site/views/get-started/guidance-for-dev/_breadcrumb.njk
- site/views/get-started/guidance-for-dev/index.njk
- site/views/get-started/index.njk
- site/views/index.njk
Updating home page content to better allow for users to access information needed. Also added pages under "Getting Started" with more info and guidance.
* Added "Basic info and getting started" page to give a bit more information about our design system
* Added "Guidance for designers"
* Renamed "Getting started" to "Guidance for developers"
* Changed the nav on the home page, moving quick links to the body and adding nav for the Getting Started
> Home page + guidance update

- packages/components/card/card.scss
- packages/components/card/macro.njk
- packages/components/card/template.njk
- site/views/design-system/components/card/card-with-icon/index.njk
- site/views/design-system/components/card/clickable-card-with-icon/index.njk
- site/views/design-system/components/card/index.njk
[https://ourfuturehealth.atlassian.net/browse/PAR-71](https://ourfuturehealth.atlassian.net/browse/PAR-71)
> Card with icon

- site/views/design-system/styles/colour/index.njk
Updated green 4 colour swatch to correct hex code.
> Fix green 4 swatch colour

- packages/core/styles/_section-break.scss
- site/views/design-system/styles/typography/index.njk
Adds black variant of section-break
https://ourfuturehealth.atlassian.net/browse/PAR-558
> feat(section-break): add black variant

- CHANGELOG.md
- package-lock.json
- package.json
> Prepare release v2.0.0-alpha.6

- packages/core/settings/_all.scss
- packages/core/settings/_tokens-colours.scss
> Colour tokens

- packages/components/task-list/_task-list.scss
- packages/ofh.scss
Addition of task list component.
> Task list component

- packages/assets/icons/icon-arrow-right-circle.svg
- packages/core/styles/_icons.scss
- site/views/design-system/styles/icons/index.njk
> Action link icon

- packages/core/styles/_icons.scss
- site/views/design-system/styles/icons/index.njk
> Updated urls to point to ofh repo instead of NHS repo

- packages/components/task-list/macro.njk
- packages/components/task-list/template.njk
- site/views/_includes/_side-nav.njk
- site/views/design-system/components/task-list/default/index.njk
- site/views/design-system/components/task-list/index.njk
- site/views/design-system/components/task-list/macro-options.json
- site/views/examples/components/task-list/index.njk
Unable to complete the work including creating the njk files needed. Support needed. 
Have added empty files for now.
> Initial work to add task list component

- package.json
- packages/components/button/_button.scss
- update base button underline spacing + thickness
- update pre-push to include lint checks
> PXG-000: update base button underline spacing + thickness

- CHANGELOG.md
- package-lock.json
- package.json
> Prepare release v3.0.0-alpha.1

- package-lock.json
- packages/core/elements/_page.scss
- packages/core/styles/_typography.scss
- site/components/example/_example.scss
- site/components/header/_header.scss
- site/components/header/macro.njk
- site/components/inset-text/_inset-text.scss
- site/components/inset-text/macro.njk
- site/styles/main.scss
- site/views/_includes/_header.njk
- site/views/_includes/layout.njk
- site/views/index.njk
> Header ds test

- packages/components/button/_button.scss
- add a default margin bottom to buttons as before
> PXG-000: add a default margin bottom to buttons

- .vscode/settings.json
- site/components/footer/_footer.scss
- site/components/footer/macro.njk
- site/styles/app/_footer.scss
- site/styles/main.scss
- site/views/_includes/_footer.njk
- site/views/_includes/layout.njk
> created doc site specific footer

- packages/components/date-input/_date-input.scss
Relates to https://dev.azure.com/eddrp-uk/eddrp/_git/eddrp-participant/pullrequest/8044
https://deploy-preview-130--ofh-design-system-docs.netlify.app/design-system/components/date-input/
> PXG-569: Add vertical-align baseline to date input

- CHANGELOG.md
- package-lock.json
- package.json
> Prepare release `3.0.3-alpha.1`

- package-lock.json
> PXG-000: Fix high security vulnerabilities in dependencies

- .github/workflows/kondukto.yml
- .github/workflows/pull-request.yml
- .github/workflows/release.yml
Utilising the action: https://github.com/ourfuturehealth/kondukto-scan
https://ourfuturehealth.atlassian.net/browse/PXG-1048
> PXG-1048: Enable security scanning using kondukto

- package-lock.json
- package.json
- packages/common/normalise-dataset.js
- packages/components/character-count/README.md
- packages/components/character-count/_character-count.scss
- packages/components/character-count/character-count.js
- packages/components/character-count/macro.njk
- packages/components/character-count/template.njk
- packages/components/task-list/_task-list.scss
- packages/ofh.js
- packages/ofh.scss
- site/scripts/main.js
- site/views/_includes/_side-nav.njk
- site/views/design-system/components/character-count/default/index.njk
- site/views/design-system/components/character-count/error/index.njk
- site/views/design-system/components/character-count/index.njk
- site/views/design-system/components/character-count/macro-options.json
- site/views/design-system/components/character-count/threshold/index.njk
- site/views/design-system/components/character-count/without-heading/index.njk
- site/views/design-system/components/character-count/word-count/index.njk
- site/views/site-map.njk
- site/views/sitemap.xml
> [RP-4020] - Character count component

- CHANGELOG.md
- package-lock.json
- package.json
A new release after the addition of the autocomplete and character count components.
> Prepare release v3.1.0-alpha.1

- CHANGELOG.md
- package-lock.json
- package.json
A new release after the update of component focus styling to improve accessibility.
> Prepare release v3.2.0-alpha.1

- CHANGELOG.md
- package-lock.json
- package.json
> Prepare release `3.3.0-alpha.1`
